apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/bhargavasachin/gitops-cicd-platform.git
      targetRevision: main
      path: helm/platform-app
      helm:
        valueFiles:
          - $values/gitops/environments/dev/values-dev.yaml
    - repoURL: https://github.com/bhargavasachin/gitops-cicd-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
